services:
  grafana:
    image: grafana/grafana-enterprise
    restart: always
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml